use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(title = "Fedi-Xanadu API", version = "1.0.0"),
    paths(
        // --- Articles ---
        crate::routes::api::articles::list_articles,
        crate::routes::api::articles::get_article,
        crate::routes::api::articles::get_article_content,
        crate::routes::api::articles::get_article_prereqs,
        crate::routes::api::articles::get_article_forks,
        crate::routes::api::articles::get_article_full,
        crate::routes::api::articles::create_article,
        crate::routes::api::articles::update_article,
        crate::routes::api::articles::delete_article,
        crate::routes::api::articles::fork_article,
        crate::routes::api::articles::convert_content,
        crate::routes::api::articles::upload_image,
        crate::routes::api::articles::get_image,
        crate::routes::api::articles::set_restricted,
        crate::routes::api::articles::grant_access,
        crate::routes::api::articles::revoke_access,
        crate::routes::api::articles::list_access_grants,
        crate::routes::api::articles::get_all_article_teaches,
        crate::routes::api::articles::get_all_article_prereqs,
        crate::routes::api::articles::get_articles_by_tag,
        crate::routes::api::articles::get_articles_by_did,
        crate::routes::api::articles::get_translations,
        crate::routes::api::articles::search_articles,
        // --- Auth ---
        crate::routes::api::auth::login,
        crate::routes::api::auth::logout,
        crate::routes::api::auth::auth_me,
        // --- Votes ---
        crate::routes::api::votes::cast_vote,
        crate::routes::api::votes::get_article_votes,
        crate::routes::api::votes::get_votes_batch,
        crate::routes::api::votes::get_my_vote,
        // --- Tags ---
        crate::routes::api::tags::list_tags,
        crate::routes::api::tags::get_tag,
        crate::routes::api::tags::search_tags,
        crate::routes::api::tags::create_tag,
        crate::routes::api::tags::update_tag_names,
        crate::routes::api::tags::set_teach,
        // --- Comments ---
        crate::routes::api::comments::list_comments,
        crate::routes::api::comments::create_comment,
        crate::routes::api::comments::update_comment,
        crate::routes::api::comments::delete_comment,
        crate::routes::api::comments::vote_comment,
        crate::routes::api::comments::get_my_comment_votes,
        // --- Bookmarks ---
        crate::routes::api::bookmarks::list_bookmarks,
        crate::routes::api::bookmarks::add_bookmark,
        crate::routes::api::bookmarks::remove_bookmark,
        crate::routes::api::bookmarks::move_bookmark,
        crate::routes::api::bookmarks::list_bookmark_folders,
        crate::routes::api::bookmarks::list_public_bookmarks,
        // --- Drafts ---
        crate::routes::api::drafts::list_drafts,
        crate::routes::api::drafts::save_draft,
        crate::routes::api::drafts::update_draft,
        crate::routes::api::drafts::delete_draft,
        crate::routes::api::drafts::publish_draft,
        // --- Follows ---
        crate::routes::api::follows::list_follows,
        crate::routes::api::follows::follow,
        crate::routes::api::follows::unfollow,
        crate::routes::api::follows::mark_seen,
        crate::routes::api::follows::following_by_did,
        crate::routes::api::follows::followers_by_did,
        // --- Series ---
        crate::routes::api::series::list_series,
        crate::routes::api::series::create_series,
        crate::routes::api::series::get_series_detail,
        crate::routes::api::series::add_series_article,
        crate::routes::api::series::remove_series_article,
        crate::routes::api::series::add_series_prereq,
        crate::routes::api::series::remove_series_prereq,
        crate::routes::api::series::all_series_articles,
        crate::routes::api::series::get_series_context,
        crate::routes::api::series::get_series_tree,
        crate::routes::api::series::reorder_articles,
        crate::routes::api::series::reorder_children,
        // --- Skills ---
        crate::routes::api::skills::list_user_skills,
        crate::routes::api::skills::light_skill,
        crate::routes::api::skills::delete_skill,
        crate::routes::api::skills::get_user_tag_tree,
        crate::routes::api::skills::add_tag_child,
        // --- Skill Trees ---
        crate::routes::api::skill_trees::list_skill_trees,
        crate::routes::api::skill_trees::create_skill_tree,
        crate::routes::api::skill_trees::get_skill_tree_detail,
        crate::routes::api::skill_trees::fork_skill_tree,
        crate::routes::api::skill_trees::add_skill_tree_edge,
        crate::routes::api::skill_trees::remove_skill_tree_edge,
        crate::routes::api::skill_trees::adopt_skill_tree,
        crate::routes::api::skill_trees::get_active_tree,
        // --- Notifications ---
        crate::routes::api::notifications::list_notifications,
        crate::routes::api::notifications::unread_count,
        crate::routes::api::notifications::mark_read,
        crate::routes::api::notifications::mark_all_read,
        // --- Profile ---
        crate::routes::api::profile::get_profile,
        crate::routes::api::profile::update_profile_links,
        // --- Questions ---
        crate::routes::api::questions::list_questions,
        crate::routes::api::questions::get_question,
        crate::routes::api::questions::create_question,
        crate::routes::api::questions::post_answer,
        crate::routes::api::questions::get_questions_by_did,
        crate::routes::api::questions::get_answers_by_did,
        crate::routes::api::questions::get_questions_by_tag,
        // --- Learned ---
        crate::routes::api::learned::list_learned,
        crate::routes::api::learned::mark_learned,
        crate::routes::api::learned::is_learned,
        crate::routes::api::learned::unmark_learned,
        // --- Interests ---
        crate::routes::api::interests::get_interests,
        crate::routes::api::interests::set_interests,
        // --- Graph ---
        crate::routes::api::graph::get_graph,
        // --- Settings ---
        crate::routes::api::settings::get_settings,
        crate::routes::api::settings::set_settings,
        // --- Keybindings ---
        crate::routes::api::keybindings::get_keybindings,
        crate::routes::api::keybindings::set_keybindings,
        // --- Books ---
        crate::routes::api::books::list_books,
        crate::routes::api::books::get_book,
        crate::routes::api::books::create_book,
        crate::routes::api::books::update_book,
        crate::routes::api::books::add_edition,
        crate::routes::api::books::get_edit_history,
        crate::routes::api::books::rate_book,
        crate::routes::api::books::set_reading_status,
        crate::routes::api::books::remove_reading_status,
        crate::routes::api::books::list_chapters,
        crate::routes::api::books::create_chapter,
        crate::routes::api::books::delete_chapter,
        crate::routes::api::books::set_chapter_progress,
        // --- Blocks ---
        crate::routes::api::blocks::block_user,
        crate::routes::api::blocks::unblock_user,
        crate::routes::api::blocks::list_blocked_users,
        crate::routes::api::blocks::list_blocked_dids,
        // --- Reports ---
        crate::routes::api::reports::create_report,
        // --- Appeals ---
        crate::routes::api::appeals::create_appeal,
        crate::routes::api::appeals::list_my_appeals,
        // --- Members ---
        crate::routes::api::members::add_member,
        crate::routes::api::members::remove_member,
        crate::routes::api::members::list_members,
        crate::routes::api::members::check_membership,
    ),
    components(schemas(
        // --- Core models ---
        fx_core::models::Article,
        fx_core::models::ArticleContent,
        fx_core::models::ArticlePrereqRow,
        fx_core::models::ForkWithTitle,
        fx_core::models::CreateArticle,
        fx_core::models::Tag,
        fx_core::models::CreateTag,
        fx_core::models::ArticlePrereq,
        fx_core::models::Draft,
        fx_core::models::SaveDraft,
        fx_core::models::UpdateDraft,
        fx_core::models::Vote,
        fx_core::models::Fork,
        fx_core::models::UserSkill,
        fx_core::models::UserBookmark,
        fx_core::models::Comment,
        // --- Content enums ---
        fx_core::content::ContentFormat,
        fx_core::content::ContentKind,
        fx_core::content::Category,
        fx_core::content::PrereqType,
        // --- Handler-local types ---
        crate::routes::api::articles::ArticleFullResponse,
        crate::routes::api::articles::ForkArticleInput,
        crate::routes::api::articles::ConvertInput,
        crate::routes::api::articles::ConvertOutput,
        crate::routes::api::articles::UpdateArticleInput,
        crate::routes::api::articles::DeleteArticleInput,
        crate::routes::api::articles::SetRestrictedInput,
        crate::routes::api::articles::AccessGrantInput,
        crate::routes::api::articles::ImageUploadResponse,
        crate::routes::api::auth::LoginInput,
        crate::routes::api::auth::LoginOutput,
        crate::routes::api::auth::AuthMeOutput,
        crate::routes::api::votes::CastVoteInput,
        crate::routes::api::votes::VoteSummary,
        crate::routes::api::votes::MyVoteOutput,
        crate::routes::api::tags::UpdateTagNamesInput,
        crate::routes::api::tags::SetTeachInput,
        crate::routes::api::comments::CreateComment,
        crate::routes::api::comments::UpdateComment,
        crate::routes::api::comments::CommentVoteInput,
        crate::routes::api::comments::CommentVoteResult,
        // --- Service types ---
        fx_core::services::article_service::ContentTeachRow,
        fx_core::services::article_service::ContentPrereqBulkRow,
        fx_core::services::article_service::AccessGrant,
        fx_core::services::vote_service::VoteSummary,
        fx_core::services::comment_service::MyCommentVote,
        fx_core::services::bookmark_service::BookmarkWithTitle,
        fx_core::services::graph_service::GraphData,
        fx_core::services::graph_service::GraphNode,
        fx_core::services::graph_service::GraphEdge,
        fx_core::services::series_service::SeriesContextItem,
        fx_core::services::book_service::Book,
        fx_core::services::book_service::BookEdition,
        fx_core::services::book_service::BookChapter,
        fx_core::services::book_service::BookRatingStats,
        fx_core::services::book_service::PurchaseLink,
    )),
    security(
        ("bearer" = [])
    )
)]
pub struct ApiDoc;
